#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Step 2: Run SFT training with LlamaFactory.
#
# Required environment variables:
#   CONFIG_YAML - Name of the SFT config file in configs/sft/ (e.g. qwen3-4b-base-sft-qwen3-8b.yaml)
#   OUTPUT_DIR  - Directory for the SFT checkpoint output
#
# Optional:
#   NUM_NODES   - Number of nodes (default: 4)
#   NUM_GPUS    - GPUs per node (default: 8)
#   MASTER_ADDR - Master node address (default: localhost)
#
# Prerequisites:
#   - LlamaFactory installed (pip install llamafactory)
#   - SFT data generated by Step 1 and registered in LlamaFactory's dataset_info.json

# NODE_RANK=0 ./configs/sft/run_sft.sh

set -euo pipefail

NUM_NODES=4
NUM_GPUS=8

MASTER_ADDR="fdbd:dccd:cdd2:2207::315"
MASTER_PORT=8000

CONFIG_YAML=${1:-qwen3-8b-base-open-thoughts3.yaml}
OUTPUT_DIR=${2:-/mnt/hdfs/wdl/ckpts/lighting-sft}

if [[ -z "${NODE_RANK:-}" ]]; then
  echo "ERROR: NODE_RANK is not set"
  echo "head_0=0, worker_0=1, worker_1=2, worker_2=3"
  exit 1
fi

echo "NUM_NODES=${NUM_NODES}"
echo "NUM_GPUS=${NUM_GPUS}"
echo "NODE_RANK=${NODE_RANK}"
echo "MASTER_ADDR=${MASTER_ADDR}"
echo "MASTER_PORT=${MASTER_PORT}"
echo "CONFIG_YAML=${CONFIG_YAML}"
echo "OUTPUT_DIR=${OUTPUT_DIR}"

torchrun \
  --nnodes "${NUM_NODES}" \
  --nproc_per_node "${NUM_GPUS}" \
  --node_rank "${NODE_RANK}" \
  --master_addr "${MASTER_ADDR}" \
  --master_port "${MASTER_PORT}" \
  -m llamafactory.cli.train \
  "configs/sft/${CONFIG_YAML}" \
  dataset_dir=configs/sft \
  output_dir="${OUTPUT_DIR}"